spring:
  aop:
      auto: true
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      max-active: 1000
      initial-size: 5
      min-idle: 5
      max-wait: 50000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      max-open-prepared-statements: 2000
  application:
    name: user-server
  profiles:
    active: dev
  cache:
    type: simple
  cloud:
    stream:
      default:
        group: ${spring.application.name}
        consumer:
          header-mode: raw
          content-type: application/json
        producer:
          header-mode: raw
          content-type: application/json
hsweb:
    app:
      name: 用户服务
      version: 1.0.0
    authorize:
      allopatric-login-modes:
          iot-cloud-user: offlineOther #异地登录模式,踢出其他地方登录的用户
    users:
      gateway-server: # 网关服务使用此用户来根据token获取用户权限信息
        username: gateway-server
        password: hsweb@gateway-server:user
server:
    port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://${eureka-host:localhost}:${eureka-port:8761}/eureka/
  instance:
    appname: ${spring.application.name}
iot:
  redis:
    clients:
      default:  #默认的redis配置
        hosts: redis://127.0.0.1:6379
        database: 0
    user-token:  # 开启redis管理user-token,只有user模块才需要开启
      enable: true
logging:
  level:
    system: TRACE
mybatis:
  mapper-locations: classpath*:org/hswebframework/iot/**/*Mapper.xml
  type-handlers-package: org.hswebframework.iot.user.enums
